// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_DETAILTIME_H
#define UI_DETAILTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_detailTime
extern void ui_detailTime_screen_init(void);
extern void ui_detailTime_screen_destroy(void);
extern lv_obj_t * ui_detailTime;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_yearMonDay;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_DefaultTime;
extern void ui_event_localTime(lv_event_t * e);
extern lv_obj_t * ui_localTime;
extern void ui_event_backMain(lv_event_t * e);
extern lv_obj_t * ui_backMain;
extern lv_obj_t * ui_Label4;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

