// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"

lv_obj_t * ui_detialLight = NULL;
lv_obj_t * ui_Switch3 = NULL;
// event funtions
void ui_event_detialLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_main04, LV_SCR_LOAD_ANIM_FADE_ON, 400, 0, &ui_main04_screen_init);
    }
}

// build funtions

void ui_detialLight_screen_init(void)
{
    ui_detialLight = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_detialLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3 = lv_switch_create(ui_detialLight);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 71);
    lv_obj_set_y(ui_Switch3, 69);
    lv_obj_set_state(ui_Switch3, LV_STATE_CHECKED, true);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_detialLight, ui_event_detialLight, LV_EVENT_ALL, NULL);

}

void ui_detialLight_screen_destroy(void)
{
    if(ui_detialLight) lv_obj_del(ui_detialLight);

    // NULL screen variables
    ui_detialLight = NULL;
    ui_Switch3 = NULL;

}
