// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"
#include "detail_dB_logic.h"
lv_obj_t * ui_detialDB = NULL;
lv_obj_t * ui_Switch2 = NULL;
// event funtions
void ui_event_detialDB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_main03, LV_SCR_LOAD_ANIM_FADE_ON, 400, 0, &ui_main03_screen_init);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * target = lv_event_get_target(e);
        bool is_on = lv_obj_has_state(target, LV_STATE_CHECKED);
        if(is_on){
            dB_init();
        }else{
            dB_deinit();
        }
    }
}

// build funtions

void ui_detialDB_screen_init(void)
{
    ui_detialDB = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_detialDB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_detialDB);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 46);
    lv_obj_set_y(ui_Switch2, 61);
    lv_obj_set_state(ui_Switch2, LV_STATE_CHECKED, true);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_detialDB, ui_event_detialDB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    dB_start();
}

void ui_detialDB_screen_destroy(void)
{
    if(ui_detialDB) lv_obj_del(ui_detialDB);

    // NULL screen variables
    ui_detialDB = NULL;
    ui_Switch2 = NULL;

}
