// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_DETAILOTA_H
#define UI_DETAILOTA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_detailOTA
extern void ui_detailOTA_screen_init(void);
extern void ui_detailOTA_screen_destroy(void);
extern lv_obj_t * ui_detailOTA;
extern lv_obj_t * ui_otaTitlePanel;
extern lv_obj_t * ui_otaTitleLabel;
extern lv_obj_t * ui_versionPanel;
extern lv_obj_t * ui_versionLabel;
extern lv_obj_t * ui_versionValue;
extern void ui_event_checkUpdate(lv_event_t * e);
extern lv_obj_t * ui_checkUpdateButton;
extern lv_obj_t * ui_checkUpdateButtonLabel;
extern lv_obj_t * ui_otaStatusLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif#ifndef UI_DETAILOTA_H
#define UI_DETAILOTA_H

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
} /*extern "C"*/
#endif