// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_DETIALDB_H
#define UI_DETIALDB_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_detialDB
extern void ui_detialDB_screen_init(void);
extern void ui_detialDB_screen_destroy(void);
extern void ui_event_detialDB(lv_event_t * e);
extern lv_obj_t * ui_detialDB;
extern lv_obj_t * ui_Switch2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

