// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"
#include "detail_temp_logic.h"
lv_obj_t * ui_detailTemperature = NULL;
lv_obj_t * ui_Switch1 = NULL;
// event funtions
void ui_event_detailTemperature(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_main02, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_main02_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED) {
        lv_obj_t * target = lv_event_get_target(e);
        bool is_on = lv_obj_has_state(target, LV_STATE_CHECKED);
        if(is_on){
            temp_init();
        }else{
            temp_deinit();
        }
    }
}

// build funtions

void ui_detailTemperature_screen_init(void)
{
    ui_detailTemperature = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_detailTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_detailTemperature);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 32);
    lv_obj_set_y(ui_Switch1, 58);
    lv_obj_set_state(ui_Switch1, LV_STATE_CHECKED, true);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_detailTemperature, ui_event_detailTemperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    temp_start();
}

void ui_detailTemperature_screen_destroy(void)
{
    if(ui_detailTemperature) lv_obj_del(ui_detailTemperature);

    // NULL screen variables
    ui_detailTemperature = NULL;
    ui_Switch1 = NULL;

}
