// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"
#include "detail_time_logic.h"
#include "string.h"
#include "esp_log.h"
#include <sys/time.h>
lv_obj_t * ui_detailTime = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_yearMonDay = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_DefaultTime = NULL;
lv_obj_t * ui_localTime = NULL;
lv_obj_t * ui_backMain = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Error01 = NULL;
// event funtions
void ui_event_localTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_localTime);
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  110);
    }
}

void ui_event_backMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main01, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_main01_screen_init);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        const char *input_text = lv_textarea_get_text(ui_localTime);
        if(input_text!=NULL && strlen(input_text)>0){
            ESP_LOGI("KeyInput","%s",input_text);
            struct tm timeinfo = {0};
            time_t new_time;
            if(sscanf(input_text, "%d-%d-%d,%d:%d:%d", 
                     &timeinfo.tm_year, &timeinfo.tm_mon, &timeinfo.tm_mday,
                     &timeinfo.tm_hour, &timeinfo.tm_min, &timeinfo.tm_sec) == 6) {
                timeinfo.tm_year -= 1900; //调整年份
                timeinfo.tm_mon -= 1;     //调整月份
                timeinfo.tm_isdst = -1;    //自动判断夏令时

                new_time = mktime(&timeinfo);//转换为时间戳
                if(new_time !=(time_t)-1){
                    struct timeval tv = {new_time, 0};//设置新的时间
                    if(settimeofday(&tv, NULL) == 0){
                        ESP_LOGI("TimeSet","时间设置成功");
                        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  220);
                        update_time_start();
                    } else {
                        ESP_LOGE("TimeSet","时间设置失败");
                    }
                }

            }
            
        }
        
    }
}

void ui_event_DefaultTime(lv_event_t *e){
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if(lv_obj_has_state(ui_DefaultTime, LV_STATE_CHECKED)){
            update_time_stop();
        }else{
            default_time_init();
            default_time_start();
            update_time_start();
        }
    }
}

// build funtions

void ui_detailTime_screen_init(void)
{
    ui_detailTime = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_detailTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_detailTime);
    lv_obj_set_width(ui_Panel1, 225);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -125);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yearMonDay = lv_label_create(ui_detailTime);
    lv_obj_set_width(ui_yearMonDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yearMonDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearMonDay, 1);
    lv_obj_set_y(ui_yearMonDay, -125);
    lv_obj_set_align(ui_yearMonDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearMonDay, "YYYY:MM:DD");
    lv_obj_set_style_text_font(ui_yearMonDay, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_detailTime);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -50);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hour = lv_label_create(ui_detailTime);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -30);
    lv_obj_set_y(ui_hour, -50);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "HH:MM:SS");
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_detailTime);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 80);
    lv_obj_set_y(ui_Label3, -50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Week");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DefaultTime = lv_switch_create(ui_detailTime);
    lv_obj_set_width(ui_DefaultTime, 50);
    lv_obj_set_height(ui_DefaultTime, 25);
    lv_obj_set_x(ui_DefaultTime, 91);
    lv_obj_set_y(ui_DefaultTime, 38);
    lv_obj_set_align(ui_DefaultTime, LV_ALIGN_CENTER);

    ui_localTime = lv_textarea_create(ui_detailTime);
    lv_obj_set_width(ui_localTime, 150);
    lv_obj_set_height(ui_localTime, 35);
    lv_obj_set_x(ui_localTime, -36);
    lv_obj_set_y(ui_localTime, 39);
    lv_obj_set_align(ui_localTime, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_localTime, "input your time");
    lv_obj_set_style_text_color(ui_localTime, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_localTime, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backMain = lv_button_create(ui_detailTime);
    lv_obj_set_width(ui_backMain, 100);
    lv_obj_set_height(ui_backMain, 50);
    lv_obj_set_x(ui_backMain, 0);
    lv_obj_set_y(ui_backMain, 110);
    lv_obj_set_align(ui_backMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backMain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backMain, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backMain, lv_color_hex(0xB7F7F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backMain, lv_color_hex(0x7EEAF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backMain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_detailTime);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 110);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "back");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_detailTime);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 237);
    lv_obj_set_height(ui_Keyboard2, 105);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 225);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    

    lv_obj_add_event_cb(ui_localTime, ui_event_localTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backMain, ui_event_backMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DefaultTime, ui_event_DefaultTime, LV_EVENT_ALL, NULL);
    default_time_init();
    default_time_start();
    update_time_start();
}

void ui_detailTime_screen_destroy(void)
{
    if(ui_detailTime) lv_obj_del(ui_detailTime);

    // NULL screen variables
    ui_detailTime = NULL;
    ui_Panel1 = NULL;
    ui_yearMonDay = NULL;
    ui_Panel3 = NULL;
    ui_hour = NULL;
    ui_Label3 = NULL;
    ui_DefaultTime = NULL;
    ui_localTime = NULL;
    ui_backMain = NULL;
    ui_Label4 = NULL;
    ui_Keyboard2 = NULL;

    update_time_stop();
}
