// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_DETIALLIGHT_H
#define UI_DETIALLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_detialLight
extern void ui_detialLight_screen_init(void);
extern void ui_detialLight_screen_destroy(void);
extern void ui_event_detialLight(lv_event_t * e);
extern void ui_event_lightBackBtn(lv_event_t * e);
extern lv_obj_t * ui_detialLight;
extern lv_obj_t * ui_lightValue;
extern lv_obj_t * ui_lightMaxVal;
extern lv_obj_t * ui_lightMinVal;
extern lv_obj_t * ui_lightAvgVal;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_lightSwitchLabel;
extern lv_obj_t * ui_lightBackBtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
