// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_DETAILTEMPERATURE_H
#define UI_DETAILTEMPERATURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_detailTemperature
extern void ui_detailTemperature_screen_init(void);
extern void ui_detailTemperature_screen_destroy(void);
extern void ui_event_detailTemperature(lv_event_t * e);
extern lv_obj_t * ui_detailTemperature;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_tempSwitchLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

