// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"

lv_obj_t * ui_main04 = NULL;
lv_obj_t * ui_lightImage = NULL;
// event funtions
void ui_event_main04(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_main01, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_main01_screen_init);
    }
}

void ui_event_lightImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detialLight, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detialLight_screen_init);
    }
}

// build funtions

void ui_main04_screen_init(void)
{
    ui_main04 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main04, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lightImage = lv_image_create(ui_main04);
    lv_image_set_src(ui_lightImage, &ui_img_light_png);
    lv_obj_set_width(ui_lightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_lightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_lightImage, ui_event_lightImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main04, ui_event_main04, LV_EVENT_ALL, NULL);

}

void ui_main04_screen_destroy(void)
{
    if(ui_main04) lv_obj_del(ui_main04);

    // NULL screen variables
    ui_main04 = NULL;
    ui_lightImage = NULL;

}
