// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_MAIN03_H
#define UI_MAIN03_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main03
extern void ui_main03_screen_init(void);
extern void ui_main03_screen_destroy(void);
extern void ui_event_main03(lv_event_t * e);
extern lv_obj_t * ui_main03;
extern void ui_event_dBImage(lv_event_t * e);
extern lv_obj_t * ui_dBImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

