// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_MAIN02_H
#define UI_MAIN02_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main02
extern void ui_main02_screen_init(void);
extern void ui_main02_screen_destroy(void);
extern void ui_event_main02(lv_event_t * e);
extern lv_obj_t * ui_main02;
extern void ui_event_tempuratureImage(lv_event_t * e);
extern lv_obj_t * ui_tempuratureImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

