// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"
#include <stdio.h>
#include "detail_dB_logic.h"
#include "detail_temp_logic.h"
lv_obj_t * ui_main01 = NULL;
lv_obj_t * ui_timeBase = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_dBTable = NULL;
lv_obj_t * ui_dBNum = NULL;
lv_obj_t * ui_temperatureTable = NULL;
lv_obj_t * ui_temperatureNum = NULL;
lv_obj_t * ui_lightTable = NULL;
lv_obj_t * ui_Label2 = NULL;

static lv_timer_t * dB_ui_timer = NULL;
// event funtions
void ui_event_main01(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_main02, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_main02_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}

void ui_event_Label1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detailTime, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_detailTime_screen_init);
    }
}


static void ui_timer_cb(lv_timer_t * timer)
{
    if(dB_get_latest_valid() && ui_dBNum){
        char dB_str[16];
        snprintf(dB_str, sizeof(dB_str), "dB:%.1f", dB_get_latest_value());
        lv_label_set_text(ui_dBNum, dB_str);
    }
    if(temp_get_latest_valid() && ui_temperatureNum){
        char temp_str[16];
        snprintf(temp_str, sizeof(temp_str), "Temp:%.1f", temp_get_latest_value());
        lv_label_set_text(ui_temperatureNum, temp_str);
    }
}
// build funtions

void ui_main01_screen_init(void)
{
    ui_main01 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeBase = lv_obj_create(ui_main01);
    lv_obj_set_width(ui_timeBase, 150);
    lv_obj_set_height(ui_timeBase, 50);
    lv_obj_set_x(ui_timeBase, 0);
    lv_obj_set_y(ui_timeBase, -100);
    lv_obj_set_align(ui_timeBase, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_timeBase, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_main01);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -100);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_Label1, 5);
    lv_label_set_text(ui_Label1, "HH:MM:SS");
    lv_obj_add_flag(ui_Label1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dBTable = lv_obj_create(ui_main01);
    lv_obj_set_width(ui_dBTable, 120);
    lv_obj_set_height(ui_dBTable, 50);
    lv_obj_set_x(ui_dBTable, 0);
    lv_obj_set_y(ui_dBTable, -40);
    lv_obj_set_align(ui_dBTable, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dBTable, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dBNum = lv_label_create(ui_main01);
    lv_obj_set_width(ui_dBNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dBNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dBNum, 0);
    lv_obj_set_y(ui_dBNum, -40);
    lv_obj_set_align(ui_dBNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dBNum, "dB:xx.x");
    lv_obj_add_flag(ui_dBNum, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_dBNum, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureTable = lv_obj_create(ui_main01);
    lv_obj_set_width(ui_temperatureTable, 150);
    lv_obj_set_height(ui_temperatureTable, 50);
    lv_obj_set_x(ui_temperatureTable, 0);
    lv_obj_set_y(ui_temperatureTable, 25);
    lv_obj_set_align(ui_temperatureTable, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_temperatureTable, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperatureNum = lv_label_create(ui_main01);
    lv_obj_set_width(ui_temperatureNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatureNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureNum, 0);
    lv_obj_set_y(ui_temperatureNum, 25);
    lv_obj_set_align(ui_temperatureNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureNum, "Temp:xx.x");
    lv_obj_set_style_text_font(ui_temperatureNum, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightTable = lv_obj_create(ui_main01);
    lv_obj_set_width(ui_lightTable, 170);
    lv_obj_set_height(ui_lightTable, 50);
    lv_obj_set_x(ui_lightTable, 0);
    lv_obj_set_y(ui_lightTable, 90);
    lv_obj_set_align(ui_lightTable, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_lightTable, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_main01);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 90);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Light:xx.x");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main01, ui_event_main01, LV_EVENT_ALL, NULL);

    if(dB_ui_timer == NULL){
        dB_ui_timer = lv_timer_create(ui_timer_cb, 100, NULL);
    }// 创建一个定时器，每100ms检查一次最新的dB值并更新UI

}

void ui_main01_screen_destroy(void)
{
    if(dB_ui_timer){
        lv_timer_del(dB_ui_timer);
        dB_ui_timer = NULL;
    }

    if(ui_main01) lv_obj_del(ui_main01);

    ui_main01 = NULL;
    ui_timeBase = NULL;
    ui_Label1 = NULL;
    ui_dBTable = NULL;
    ui_dBNum = NULL;
    ui_temperatureTable = NULL;
    ui_temperatureNum = NULL;
    ui_lightTable = NULL;
    ui_Label2 = NULL;

}