// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"

lv_obj_t * ui_main02 = NULL;
lv_obj_t * ui_tempuratureImage = NULL;
// event funtions
void ui_event_main02(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_main03, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_main03_screen_init);
    }
}

void ui_event_tempuratureImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_detailTemperature, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_detailTemperature_screen_init);
    }
}

// build funtions

void ui_main02_screen_init(void)
{
    ui_main02 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempuratureImage = lv_image_create(ui_main02);
    lv_image_set_src(ui_tempuratureImage, &ui_img_temperature_png);
    lv_obj_set_width(ui_tempuratureImage, lv_pct(50));
    lv_obj_set_height(ui_tempuratureImage, lv_pct(50));
    lv_obj_set_align(ui_tempuratureImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempuratureImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_tempuratureImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_tempuratureImage, ui_event_tempuratureImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main02, ui_event_main02, LV_EVENT_ALL, NULL);

}

void ui_main02_screen_destroy(void)
{
    if(ui_main02) lv_obj_del(ui_main02);

    // NULL screen variables
    ui_main02 = NULL;
    ui_tempuratureImage = NULL;

}
