// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_MAIN04_H
#define UI_MAIN04_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main04
extern void ui_main04_screen_init(void);
extern void ui_main04_screen_destroy(void);
extern void ui_event_main04(lv_event_t * e);
extern lv_obj_t * ui_main04;
extern void ui_event_lightImage(lv_event_t * e);
extern lv_obj_t * ui_lightImage;
extern lv_obj_t * ui_lightTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

