// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_MAIN01_H
#define UI_MAIN01_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main01
extern void ui_main01_screen_init(void);
extern void ui_main01_screen_destroy(void);
extern void ui_event_main01(lv_event_t * e);
extern lv_obj_t * ui_main01;
extern lv_obj_t * ui_timeBase;
extern void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_dBTable;
extern lv_obj_t * ui_dBNum;
extern lv_obj_t * ui_temperatureTable;
extern lv_obj_t * ui_temperatureNum;
extern lv_obj_t * ui_lightTable;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

