// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_WIFI;
extern void ui_event_Label5(lv_event_t * e);
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_WIFISwitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

