// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"

lv_obj_t * ui_ScreenLock = NULL;
lv_obj_t * ui_Panel2 = NULL;
// event funtions
void ui_event_ScreenLock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main01, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0, &ui_main01_screen_init);
        ui_ScreenLock = NULL;
        ui_Panel2 = NULL;

    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        screenLockBall_Animation(ui_Panel2, 0);
    }
}

// build funtions

void ui_ScreenLock_screen_init(void)
{
    ui_ScreenLock = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_ScreenLock);
    lv_obj_set_width(ui_Panel2, 40);
    lv_obj_set_height(ui_Panel2, 40);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -100);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_Panel2, 1);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenLock, ui_event_ScreenLock, LV_EVENT_ALL, NULL);

}

void ui_ScreenLock_screen_destroy(void)
{
    if(ui_ScreenLock) lv_obj_del(ui_ScreenLock);

    // NULL screen variables
    ui_ScreenLock = NULL;
    ui_Panel2 = NULL;

}
