// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_SCREENLOCK_H
#define UI_SCREENLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLock
extern void ui_ScreenLock_screen_init(void);
extern void ui_ScreenLock_screen_destroy(void);
extern void ui_event_ScreenLock(lv_event_t * e);
extern lv_obj_t * ui_ScreenLock;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lockText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

