// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"
#include "my_wifi.h"
lv_obj_t * ui_WIFIsetting = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_WIFIChoice = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_passwordContainer = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_WIFIsetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_setting_screen_init);
    }
}

void ui_event_value_changed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lv_obj_remove_flag(ui_passwordContainer, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_event_WIFIConnect(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_READY) {
        // 获取输入的密码和选择的WIFI
        const char *password = lv_textarea_get_text(ui_TextArea1);
        char selected_wifi[32];
        lv_dropdown_get_selected_str(ui_WIFIChoice, selected_wifi, sizeof(selected_wifi));
        //调用连接WIFI的函数，传入selected_wifi和password
        bool connect_result = wifi_connect(selected_wifi, password);
        //将界面隐藏或者提示错误信息
        if(connect_result) {
            //连接成功，隐藏界面或者显示成功提示
            lv_obj_add_flag(ui_passwordContainer, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
        } else {
            //连接失败，显示错误提示
            lv_label_set_text(ui_Label7, "Error:");
        }
    }
}

// build funtions

void ui_WIFIsetting_screen_init(void)
{
    ui_WIFIsetting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WIFIsetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_WIFIsetting);
    lv_obj_set_width(ui_Panel5, 230);
    lv_obj_set_height(ui_Panel5, 40);
    lv_obj_set_x(ui_Panel5, 5);
    lv_obj_set_y(ui_Panel5, 10);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WIFIChoice = lv_dropdown_create(ui_WIFIsetting);
    lv_dropdown_set_options(ui_WIFIChoice, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_WIFIChoice, 230);
    lv_obj_set_height(ui_WIFIChoice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFIChoice, 0);
    lv_obj_set_y(ui_WIFIChoice, -90);
    lv_obj_set_align(ui_WIFIChoice, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIChoice, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label6 = lv_label_create(ui_WIFIsetting);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 20);
    lv_obj_set_y(ui_Label6, 20);
    lv_label_set_text(ui_Label6, "please choice WIFI");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordContainer = lv_obj_create(ui_WIFIsetting);
    lv_obj_remove_style_all(ui_passwordContainer);
    lv_obj_set_width(ui_passwordContainer, 230);
    lv_obj_set_height(ui_passwordContainer, 30);
    lv_obj_set_x(ui_passwordContainer, 0);
    lv_obj_set_y(ui_passwordContainer, -45);
    lv_obj_set_align(ui_passwordContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_passwordContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_passwordContainer,LV_OBJ_FLAG_HIDDEN);      /// Flags

    ui_Panel6 = lv_obj_create(ui_passwordContainer);
    lv_obj_set_width(ui_Panel6, 230);
    lv_obj_set_height(ui_Panel6, 30);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Label7, -5);
    lv_label_set_text(ui_Label7, "password:");

    ui_TextArea1 = lv_textarea_create(ui_Panel6);
    lv_obj_set_width(ui_TextArea1, 132);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_TextArea1, 75);
    lv_obj_set_y(ui_TextArea1, 0);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 25);
    lv_textarea_set_one_line(ui_TextArea1, true);

    ui_Keyboard1 = lv_keyboard_create(ui_WIFIsetting);
    lv_obj_set_width(ui_Keyboard1, 238);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 1);
    lv_obj_set_y(ui_Keyboard1, 57);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1,LV_OBJ_FLAG_HIDDEN);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);

    lv_obj_add_event_cb(ui_WIFIsetting, ui_event_WIFIsetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WIFIChoice, ui_event_value_changed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_WIFIConnect, LV_EVENT_READY, NULL);
    
}

void ui_WIFIsetting_screen_destroy(void)
{
    if(ui_WIFIsetting) lv_obj_del(ui_WIFIsetting);

    // NULL screen variables
    ui_WIFIsetting = NULL;
    ui_Panel5 = NULL;
    ui_WIFIChoice = NULL;
    ui_Label6 = NULL;
    ui_passwordContainer = NULL;
    ui_Panel6 = NULL;
    ui_Label7 = NULL;
    ui_TextArea1 = NULL;
    ui_Keyboard1 = NULL;
}
