// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef UI_WIFISETTING_H
#define UI_WIFISETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WIFIsetting
extern void ui_WIFIsetting_screen_init(void);
extern void ui_WIFIsetting_screen_destroy(void);
extern void ui_event_WIFIsetting(lv_event_t * e);
extern lv_obj_t * ui_WIFIsetting;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_WIFIChoice;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_passwordContainer;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

