// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef _ESP_CAMERA_UI_H
#define _ESP_CAMERA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenLock.h"
#include "screens/ui_main01.h"
#include "screens/ui_main02.h"
#include "screens/ui_main03.h"
#include "screens/ui_main04.h"
#include "screens/ui_detailTime.h"
#include "screens/ui_detailTemperature.h"
#include "screens/ui_detialDB.h"
#include "screens/ui_detialLight.h"
#include "screens/ui_setting.h"
#include "screens/ui_WIFIsetting.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * screenLockBall_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * timeKeyboard_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_db_png);    // assets/dB.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
