// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: 01

#include "../ui.h"

void ui_comp_Panel1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel2_create_hook(lv_obj_t * comp)
{
}
