// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#ifndef _UI_COMP_PANEL2_H
#define _UI_COMP_PANEL2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel2
#define UI_COMP_PANEL2_PANEL2 0
#define _UI_COMP_PANEL2_NUM 1
lv_obj_t * ui_Panel2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
