// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: ESP-Camera

#include "../ui.h"

// COMPONENT Panel2

lv_obj_t * ui_Panel2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel2;
    cui_Panel2 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel2, 150);
    lv_obj_set_height(cui_Panel2, 10);
    lv_obj_set_x(cui_Panel2, 0);
    lv_obj_set_y(cui_Panel2, 75);
    lv_obj_set_align(cui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL2_NUM);
    children[UI_COMP_PANEL2_PANEL2] = cui_Panel2;
    lv_obj_add_event_cb(cui_Panel2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel2_create_hook(cui_Panel2);
    return cui_Panel2;
}

